### PR TITLE
Update default.js

### PR DESCRIPTION
**Pull request by Gera-IC**
dtexpire>=NOW()

### CODE REVIEW

**Comment by Gera-IC** [comment]
also is needed add set to db query
db.one('tbl_oauth').fields('name').id(filter.client_id).where('accesstoken', filter.client_secret).set('oauth');

**Comment by petersirka** [comment]
OMG :-D thank you.

**Comment by petersirka** [comment]
> ).

Where?

**Comment by petersirka** [comment]
> also is needed add set to db query
> db.one('tbl_oauth').fields('name').id(filter.client_id).where('accesstoken', filter.client_secret).set('oauth');

Where?

**Pull request merged**
